FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# COPY ./src ./src
# COPY ./public ./public
# COPY ./next.config.ts ./next.config.ts
# COPY ./tsconfig.json ./tsconfig.json
# COPY ./postcss.config.mjs ./postcss.config.mjs
# COPY ./eslint.config.mjs ./eslint.config.mjs
# COPY ./tailwind.config.js ./tailwind.config.js

ENV PORT=3000
EXPOSE 3000
CMD ["npm","run","dev","--","-p","3000"]




# FROM node:20-alpine AS build
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY ./src ./src
# COPY ./public ./public
# COPY ./next.config.ts ./next.config.ts
# COPY ./tsconfig.json ./tsconfig.json
# COPY ./postcss.config.mjs ./postcss.config.mjs
# COPY ./eslint.config.mjs ./eslint.config.mjs
# COPY ./tailwind.config.js ./tailwind.config.js

# RUN npm run build

# FROM node:20-alpine
# WORKDIR /app
# ENV NODE_ENV=production
# COPY --from=build /app/package*.json ./
# RUN npm ci --omit=dev --ignore-scripts
# COPY --from=build /app/.next ./.next
# COPY --from=build /app/public ./public
# ENV PORT=3000
# EXPOSE 3000
# CMD ["npm","run","start","--","-p","3000"]